// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/openai-go-sdk/v4/pkg/models/shared"
	"net/http"
)

type CancelFineTuningJobRequest struct {
	// The ID of the fine-tuning job to cancel.
	//
	FineTuningJobID string `pathParam:"style=simple,explode=false,name=fine_tuning_job_id"`
}

func (o *CancelFineTuningJobRequest) GetFineTuningJobID() string {
	if o == nil {
		return ""
	}
	return o.FineTuningJobID
}

type CancelFineTuningJobResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	FineTuningJob *shared.FineTuningJob
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CancelFineTuningJobResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CancelFineTuningJobResponse) GetFineTuningJob() *shared.FineTuningJob {
	if o == nil {
		return nil
	}
	return o.FineTuningJob
}

func (o *CancelFineTuningJobResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CancelFineTuningJobResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
