// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/openai-go-sdk/v4/pkg/models/shared"
	"net/http"
)

type CancelRunRequest struct {
	// The ID of the run to cancel.
	RunID string `pathParam:"style=simple,explode=false,name=run_id"`
	// The ID of the thread to which this run belongs.
	ThreadID string `pathParam:"style=simple,explode=false,name=thread_id"`
}

func (o *CancelRunRequest) GetRunID() string {
	if o == nil {
		return ""
	}
	return o.RunID
}

func (o *CancelRunRequest) GetThreadID() string {
	if o == nil {
		return ""
	}
	return o.ThreadID
}

type CancelRunResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	RunObject *shared.RunObject
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CancelRunResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CancelRunResponse) GetRunObject() *shared.RunObject {
	if o == nil {
		return nil
	}
	return o.RunObject
}

func (o *CancelRunResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CancelRunResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
