// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/openai-go-sdk/v2/pkg/models/shared"
	"net/http"
)

type CreateTranscriptionResponse struct {
	ContentType string
	// OK
	CreateTranscriptionResponse *shared.CreateTranscriptionResponse
	StatusCode                  int
	RawResponse                 *http.Response
}

func (o *CreateTranscriptionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateTranscriptionResponse) GetCreateTranscriptionResponse() *shared.CreateTranscriptionResponse {
	if o == nil {
		return nil
	}
	return o.CreateTranscriptionResponse
}

func (o *CreateTranscriptionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateTranscriptionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
