// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/openai-go-sdk/v2/pkg/models/shared"
	"net/http"
)

type CreateFineTuningJobResponse struct {
	ContentType string
	// OK
	FineTuningJob *shared.FineTuningJob
	StatusCode    int
	RawResponse   *http.Response
}

func (o *CreateFineTuningJobResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateFineTuningJobResponse) GetFineTuningJob() *shared.FineTuningJob {
	if o == nil {
		return nil
	}
	return o.FineTuningJob
}

func (o *CreateFineTuningJobResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateFineTuningJobResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
