// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CreateImageEditResponse struct {
	ContentType string
	// OK
	ImagesResponse interface{}
	StatusCode     int
	RawResponse    *http.Response
}
