// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/openai-go-sdk/pkg/models/shared"
	"net/http"
)

type CreateClassificationResponse struct {
	ContentType string
	// OK
	CreateClassificationResponse *shared.CreateClassificationResponse
	StatusCode                   int
	RawResponse                  *http.Response
}
