// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/openai-go-sdk/pkg/models/shared"
	"net/http"
)

type CreateSearchRequest struct {
	CreateSearchRequest shared.CreateSearchRequest `request:"mediaType=application/json"`
	// The ID of the engine to use for this request.  You can select one of `ada`, `babbage`, `curie`, or `davinci`.
	EngineID string `pathParam:"style=simple,explode=false,name=engine_id"`
}

type CreateSearchResponse struct {
	ContentType string
	// OK
	CreateSearchResponse *shared.CreateSearchResponse
	StatusCode           int
	RawResponse          *http.Response
}
