// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/openai-go-sdk/v2/pkg/models/shared"
	"net/http"
)

type CreateChatCompletionResponse struct {
	ContentType string
	// OK
	CreateChatCompletionResponse *shared.CreateChatCompletionResponse
	StatusCode                   int
	RawResponse                  *http.Response
}

func (o *CreateChatCompletionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateChatCompletionResponse) GetCreateChatCompletionResponse() *shared.CreateChatCompletionResponse {
	if o == nil {
		return nil
	}
	return o.CreateChatCompletionResponse
}

func (o *CreateChatCompletionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateChatCompletionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
