// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CreateFineTuneResponse struct {
	ContentType string
	// OK
	FineTune    interface{}
	StatusCode  int
	RawResponse *http.Response
}
