// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CreateFileResponse struct {
	ContentType string
	// OK
	OpenAIFile  interface{}
	StatusCode  int
	RawResponse *http.Response
}
