// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/openai-go-sdk/v2/pkg/models/shared"
	"net/http"
)

type CreateFileResponse struct {
	ContentType string
	// OK
	OpenAIFile  *shared.OpenAIFile
	StatusCode  int
	RawResponse *http.Response
}

func (o *CreateFileResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateFileResponse) GetOpenAIFile() *shared.OpenAIFile {
	if o == nil {
		return nil
	}
	return o.OpenAIFile
}

func (o *CreateFileResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateFileResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
