// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/openai-go-sdk/v4/pkg/models/shared"
	"net/http"
)

type DeleteAssistantRequest struct {
	// The ID of the assistant to delete.
	AssistantID string `pathParam:"style=simple,explode=false,name=assistant_id"`
}

func (o *DeleteAssistantRequest) GetAssistantID() string {
	if o == nil {
		return ""
	}
	return o.AssistantID
}

type DeleteAssistantResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	DeleteAssistantResponse *shared.DeleteAssistantResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteAssistantResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteAssistantResponse) GetDeleteAssistantResponse() *shared.DeleteAssistantResponse {
	if o == nil {
		return nil
	}
	return o.DeleteAssistantResponse
}

func (o *DeleteAssistantResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteAssistantResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
