// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/openai-go-sdk/v4/pkg/models/shared"
	"net/http"
)

type GetAssistantRequest struct {
	// The ID of the assistant to retrieve.
	AssistantID string `pathParam:"style=simple,explode=false,name=assistant_id"`
}

func (o *GetAssistantRequest) GetAssistantID() string {
	if o == nil {
		return ""
	}
	return o.AssistantID
}

type GetAssistantResponse struct {
	// OK
	AssistantObject *shared.AssistantObject
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetAssistantResponse) GetAssistantObject() *shared.AssistantObject {
	if o == nil {
		return nil
	}
	return o.AssistantObject
}

func (o *GetAssistantResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAssistantResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAssistantResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
