// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/openai-go-sdk/v4/pkg/models/shared"
	"net/http"
)

type GetRunStepRequest struct {
	// The ID of the run to which the run step belongs.
	RunID string `pathParam:"style=simple,explode=false,name=run_id"`
	// The ID of the run step to retrieve.
	StepID string `pathParam:"style=simple,explode=false,name=step_id"`
	// The ID of the thread to which the run and run step belongs.
	ThreadID string `pathParam:"style=simple,explode=false,name=thread_id"`
}

func (o *GetRunStepRequest) GetRunID() string {
	if o == nil {
		return ""
	}
	return o.RunID
}

func (o *GetRunStepRequest) GetStepID() string {
	if o == nil {
		return ""
	}
	return o.StepID
}

func (o *GetRunStepRequest) GetThreadID() string {
	if o == nil {
		return ""
	}
	return o.ThreadID
}

type GetRunStepResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	RunStepObject *shared.RunStepObject
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetRunStepResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetRunStepResponse) GetRunStepObject() *shared.RunStepObject {
	if o == nil {
		return nil
	}
	return o.RunStepObject
}

func (o *GetRunStepResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetRunStepResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
