// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/openai-go-sdk/v4/pkg/models/shared"
	"github.com/speakeasy-sdks/openai-go-sdk/v4/pkg/utils"
	"net/http"
)

type ListPaginatedFineTuningJobsRequest struct {
	// Identifier for the last job from the previous pagination request.
	After *string `queryParam:"style=form,explode=true,name=after"`
	// Number of fine-tuning jobs to retrieve.
	Limit *int64 `default:"20" queryParam:"style=form,explode=true,name=limit"`
}

func (l ListPaginatedFineTuningJobsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListPaginatedFineTuningJobsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListPaginatedFineTuningJobsRequest) GetAfter() *string {
	if o == nil {
		return nil
	}
	return o.After
}

func (o *ListPaginatedFineTuningJobsRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

type ListPaginatedFineTuningJobsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	ListPaginatedFineTuningJobsResponse *shared.ListPaginatedFineTuningJobsResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ListPaginatedFineTuningJobsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListPaginatedFineTuningJobsResponse) GetListPaginatedFineTuningJobsResponse() *shared.ListPaginatedFineTuningJobsResponse {
	if o == nil {
		return nil
	}
	return o.ListPaginatedFineTuningJobsResponse
}

func (o *ListPaginatedFineTuningJobsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListPaginatedFineTuningJobsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
