// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ChatCompletionRequestMessageRoleEnum - The role of the author of this message.
type ChatCompletionRequestMessageRoleEnum string

const (
	ChatCompletionRequestMessageRoleEnumSystem    ChatCompletionRequestMessageRoleEnum = "system"
	ChatCompletionRequestMessageRoleEnumUser      ChatCompletionRequestMessageRoleEnum = "user"
	ChatCompletionRequestMessageRoleEnumAssistant ChatCompletionRequestMessageRoleEnum = "assistant"
)

func (e ChatCompletionRequestMessageRoleEnum) ToPointer() *ChatCompletionRequestMessageRoleEnum {
	return &e
}

func (e *ChatCompletionRequestMessageRoleEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "system":
		fallthrough
	case "user":
		fallthrough
	case "assistant":
		*e = ChatCompletionRequestMessageRoleEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ChatCompletionRequestMessageRoleEnum: %v", v)
	}
}

type ChatCompletionRequestMessage struct {
	// The contents of the message
	Content string `json:"content"`
	// The name of the user in a multi-user chat
	Name *string `json:"name,omitempty"`
	// The role of the author of this message.
	Role ChatCompletionRequestMessageRoleEnum `json:"role"`
}
