// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ChatCompletionRequestSystemMessageRole - The role of the messages author, in this case `system`.
type ChatCompletionRequestSystemMessageRole string

const (
	ChatCompletionRequestSystemMessageRoleSystem ChatCompletionRequestSystemMessageRole = "system"
)

func (e ChatCompletionRequestSystemMessageRole) ToPointer() *ChatCompletionRequestSystemMessageRole {
	return &e
}

func (e *ChatCompletionRequestSystemMessageRole) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "system":
		*e = ChatCompletionRequestSystemMessageRole(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ChatCompletionRequestSystemMessageRole: %v", v)
	}
}

type ChatCompletionRequestSystemMessage struct {
	// The contents of the system message.
	Content string `json:"content"`
	// An optional name for the participant. Provides the model information to differentiate between participants of the same role.
	Name *string `json:"name,omitempty"`
	// The role of the messages author, in this case `system`.
	Role ChatCompletionRequestSystemMessageRole `json:"role"`
}

func (o *ChatCompletionRequestSystemMessage) GetContent() string {
	if o == nil {
		return ""
	}
	return o.Content
}

func (o *ChatCompletionRequestSystemMessage) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ChatCompletionRequestSystemMessage) GetRole() ChatCompletionRequestSystemMessageRole {
	if o == nil {
		return ChatCompletionRequestSystemMessageRole("")
	}
	return o.Role
}
