// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"errors"
	"github.com/speakeasy-sdks/openai-go-sdk/v3/pkg/utils"
)

type ChatCompletionRequestMessageContentPartType string

const (
	ChatCompletionRequestMessageContentPartTypeChatCompletionRequestMessageContentPartText  ChatCompletionRequestMessageContentPartType = "ChatCompletionRequestMessageContentPartText"
	ChatCompletionRequestMessageContentPartTypeChatCompletionRequestMessageContentPartImage ChatCompletionRequestMessageContentPartType = "ChatCompletionRequestMessageContentPartImage"
)

type ChatCompletionRequestMessageContentPart struct {
	ChatCompletionRequestMessageContentPartText  *ChatCompletionRequestMessageContentPartText
	ChatCompletionRequestMessageContentPartImage *ChatCompletionRequestMessageContentPartImage

	Type ChatCompletionRequestMessageContentPartType
}

func CreateChatCompletionRequestMessageContentPartChatCompletionRequestMessageContentPartText(chatCompletionRequestMessageContentPartText ChatCompletionRequestMessageContentPartText) ChatCompletionRequestMessageContentPart {
	typ := ChatCompletionRequestMessageContentPartTypeChatCompletionRequestMessageContentPartText

	return ChatCompletionRequestMessageContentPart{
		ChatCompletionRequestMessageContentPartText: &chatCompletionRequestMessageContentPartText,
		Type: typ,
	}
}

func CreateChatCompletionRequestMessageContentPartChatCompletionRequestMessageContentPartImage(chatCompletionRequestMessageContentPartImage ChatCompletionRequestMessageContentPartImage) ChatCompletionRequestMessageContentPart {
	typ := ChatCompletionRequestMessageContentPartTypeChatCompletionRequestMessageContentPartImage

	return ChatCompletionRequestMessageContentPart{
		ChatCompletionRequestMessageContentPartImage: &chatCompletionRequestMessageContentPartImage,
		Type: typ,
	}
}

func (u *ChatCompletionRequestMessageContentPart) UnmarshalJSON(data []byte) error {

	chatCompletionRequestMessageContentPartText := ChatCompletionRequestMessageContentPartText{}
	if err := utils.UnmarshalJSON(data, &chatCompletionRequestMessageContentPartText, "", true, true); err == nil {
		u.ChatCompletionRequestMessageContentPartText = &chatCompletionRequestMessageContentPartText
		u.Type = ChatCompletionRequestMessageContentPartTypeChatCompletionRequestMessageContentPartText
		return nil
	}

	chatCompletionRequestMessageContentPartImage := ChatCompletionRequestMessageContentPartImage{}
	if err := utils.UnmarshalJSON(data, &chatCompletionRequestMessageContentPartImage, "", true, true); err == nil {
		u.ChatCompletionRequestMessageContentPartImage = &chatCompletionRequestMessageContentPartImage
		u.Type = ChatCompletionRequestMessageContentPartTypeChatCompletionRequestMessageContentPartImage
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u ChatCompletionRequestMessageContentPart) MarshalJSON() ([]byte, error) {
	if u.ChatCompletionRequestMessageContentPartText != nil {
		return utils.MarshalJSON(u.ChatCompletionRequestMessageContentPartText, "", true)
	}

	if u.ChatCompletionRequestMessageContentPartImage != nil {
		return utils.MarshalJSON(u.ChatCompletionRequestMessageContentPartImage, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}
