// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ChatCompletionRequestMessageRole - The role of the author of this message.
type ChatCompletionRequestMessageRole string

const (
	ChatCompletionRequestMessageRoleSystem    ChatCompletionRequestMessageRole = "system"
	ChatCompletionRequestMessageRoleUser      ChatCompletionRequestMessageRole = "user"
	ChatCompletionRequestMessageRoleAssistant ChatCompletionRequestMessageRole = "assistant"
)

func (e ChatCompletionRequestMessageRole) ToPointer() *ChatCompletionRequestMessageRole {
	return &e
}

func (e *ChatCompletionRequestMessageRole) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "system":
		fallthrough
	case "user":
		fallthrough
	case "assistant":
		*e = ChatCompletionRequestMessageRole(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ChatCompletionRequestMessageRole: %v", v)
	}
}

type ChatCompletionRequestMessage struct {
	// The contents of the message
	Content string `json:"content"`
	// The name of the user in a multi-user chat
	Name *string `json:"name,omitempty"`
	// The role of the author of this message.
	Role ChatCompletionRequestMessageRole `json:"role"`
}
