// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ChatCompletionResponseMessageRole - The role of the author of this message.
type ChatCompletionResponseMessageRole string

const (
	ChatCompletionResponseMessageRoleSystem    ChatCompletionResponseMessageRole = "system"
	ChatCompletionResponseMessageRoleUser      ChatCompletionResponseMessageRole = "user"
	ChatCompletionResponseMessageRoleAssistant ChatCompletionResponseMessageRole = "assistant"
)

func (e ChatCompletionResponseMessageRole) ToPointer() *ChatCompletionResponseMessageRole {
	return &e
}

func (e *ChatCompletionResponseMessageRole) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "system":
		fallthrough
	case "user":
		fallthrough
	case "assistant":
		*e = ChatCompletionResponseMessageRole(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ChatCompletionResponseMessageRole: %v", v)
	}
}

type ChatCompletionResponseMessage struct {
	// The contents of the message
	Content string `json:"content"`
	// The role of the author of this message.
	Role ChatCompletionResponseMessageRole `json:"role"`
}
