// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ChatCompletionResponseMessageRoleEnum - The role of the author of this message.
type ChatCompletionResponseMessageRoleEnum string

const (
	ChatCompletionResponseMessageRoleEnumSystem    ChatCompletionResponseMessageRoleEnum = "system"
	ChatCompletionResponseMessageRoleEnumUser      ChatCompletionResponseMessageRoleEnum = "user"
	ChatCompletionResponseMessageRoleEnumAssistant ChatCompletionResponseMessageRoleEnum = "assistant"
)

func (e ChatCompletionResponseMessageRoleEnum) ToPointer() *ChatCompletionResponseMessageRoleEnum {
	return &e
}

func (e *ChatCompletionResponseMessageRoleEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "system":
		fallthrough
	case "user":
		fallthrough
	case "assistant":
		*e = ChatCompletionResponseMessageRoleEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ChatCompletionResponseMessageRoleEnum: %v", v)
	}
}

type ChatCompletionResponseMessage struct {
	// The contents of the message
	Content string `json:"content"`
	// The role of the author of this message.
	Role ChatCompletionResponseMessageRoleEnum `json:"role"`
}
