// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateEmbeddingRequest struct {
	// Input text to get embeddings for, encoded as a string or array of tokens. To get embeddings for multiple inputs in a single request, pass an array of strings or array of token arrays. Each input must not exceed 8192 tokens in length.
	//
	Input interface{} `json:"input"`
	Model interface{} `json:"model"`
	User  interface{} `json:"user,omitempty"`
}
