// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateFileRequestFile struct {
	Content []byte `multipartForm:"content"`
	File    string `multipartForm:"name=file"`
}

func (o *CreateFileRequestFile) GetContent() []byte {
	if o == nil {
		return []byte{}
	}
	return o.Content
}

func (o *CreateFileRequestFile) GetFile() string {
	if o == nil {
		return ""
	}
	return o.File
}

type CreateFileRequest struct {
	// Name of the [JSON Lines](https://jsonlines.readthedocs.io/en/latest/) file to be uploaded.
	//
	// If the `purpose` is set to "fine-tune", the file will be used for fine-tuning.
	//
	File CreateFileRequestFile `multipartForm:"file"`
	// The intended purpose of the uploaded documents.
	//
	// Use "fine-tune" for [fine-tuning](/docs/api-reference/fine-tuning). This allows us to validate the format of the uploaded file.
	//
	Purpose string `multipartForm:"name=purpose"`
}

func (o *CreateFileRequest) GetFile() CreateFileRequestFile {
	if o == nil {
		return CreateFileRequestFile{}
	}
	return o.File
}

func (o *CreateFileRequest) GetPurpose() string {
	if o == nil {
		return ""
	}
	return o.Purpose
}
