// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateImageRequestResponseFormatEnum - The format in which the generated images are returned. Must be one of `url` or `b64_json`.
type CreateImageRequestResponseFormatEnum string

const (
	CreateImageRequestResponseFormatEnumURL     CreateImageRequestResponseFormatEnum = "url"
	CreateImageRequestResponseFormatEnumB64JSON CreateImageRequestResponseFormatEnum = "b64_json"
)

// CreateImageRequestSizeEnum - The size of the generated images. Must be one of `256x256`, `512x512`, or `1024x1024`.
type CreateImageRequestSizeEnum string

const (
	CreateImageRequestSizeEnumTwoHundredAndFiftySixx256     CreateImageRequestSizeEnum = "256x256"
	CreateImageRequestSizeEnumFiveHundredAndTwelvex512      CreateImageRequestSizeEnum = "512x512"
	CreateImageRequestSizeEnumOneThousandAndTwentyFourx1024 CreateImageRequestSizeEnum = "1024x1024"
)

type CreateImageRequest struct {
	// The number of images to generate. Must be between 1 and 10.
	N *int64 `json:"n,omitempty"`
	// A text description of the desired image(s). The maximum length is 1000 characters.
	Prompt string `json:"prompt"`
	// The format in which the generated images are returned. Must be one of `url` or `b64_json`.
	ResponseFormat *CreateImageRequestResponseFormatEnum `json:"response_format,omitempty"`
	// The size of the generated images. Must be one of `256x256`, `512x512`, or `1024x1024`.
	Size *CreateImageRequestSizeEnum `json:"size,omitempty"`
	User interface{}                 `json:"user,omitempty"`
}
