// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateEmbeddingResponseUsage - The usage information for the request.
type CreateEmbeddingResponseUsage struct {
	// The number of tokens used by the prompt.
	PromptTokens int64 `json:"prompt_tokens"`
	// The total number of tokens used by the request.
	TotalTokens int64 `json:"total_tokens"`
}

func (o *CreateEmbeddingResponseUsage) GetPromptTokens() int64 {
	if o == nil {
		return 0
	}
	return o.PromptTokens
}

func (o *CreateEmbeddingResponseUsage) GetTotalTokens() int64 {
	if o == nil {
		return 0
	}
	return o.TotalTokens
}

type CreateEmbeddingResponse struct {
	// The list of embeddings generated by the model.
	Data []Embedding `json:"data"`
	// The name of the model used to generate the embedding.
	Model string `json:"model"`
	// The object type, which is always "embedding".
	Object string `json:"object"`
	// The usage information for the request.
	Usage CreateEmbeddingResponseUsage `json:"usage"`
}

func (o *CreateEmbeddingResponse) GetData() []Embedding {
	if o == nil {
		return []Embedding{}
	}
	return o.Data
}

func (o *CreateEmbeddingResponse) GetModel() string {
	if o == nil {
		return ""
	}
	return o.Model
}

func (o *CreateEmbeddingResponse) GetObject() string {
	if o == nil {
		return ""
	}
	return o.Object
}

func (o *CreateEmbeddingResponse) GetUsage() CreateEmbeddingResponseUsage {
	if o == nil {
		return CreateEmbeddingResponseUsage{}
	}
	return o.Usage
}
