// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateTranslationResponseJSON struct {
	Text string `json:"text"`
}

func (o *CreateTranslationResponseJSON) GetText() string {
	if o == nil {
		return ""
	}
	return o.Text
}
