// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ListRunStepsResponse struct {
	Data    []RunStepObject `json:"data"`
	FirstID string          `json:"first_id"`
	HasMore bool            `json:"has_more"`
	LastID  string          `json:"last_id"`
	Object  string          `json:"object"`
}

func (o *ListRunStepsResponse) GetData() []RunStepObject {
	if o == nil {
		return []RunStepObject{}
	}
	return o.Data
}

func (o *ListRunStepsResponse) GetFirstID() string {
	if o == nil {
		return ""
	}
	return o.FirstID
}

func (o *ListRunStepsResponse) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *ListRunStepsResponse) GetLastID() string {
	if o == nil {
		return ""
	}
	return o.LastID
}

func (o *ListRunStepsResponse) GetObject() string {
	if o == nil {
		return ""
	}
	return o.Object
}
