// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ListRunsResponse struct {
	Data    []RunObject `json:"data"`
	FirstID string      `json:"first_id"`
	HasMore bool        `json:"has_more"`
	LastID  string      `json:"last_id"`
	Object  string      `json:"object"`
}

func (o *ListRunsResponse) GetData() []RunObject {
	if o == nil {
		return []RunObject{}
	}
	return o.Data
}

func (o *ListRunsResponse) GetFirstID() string {
	if o == nil {
		return ""
	}
	return o.FirstID
}

func (o *ListRunsResponse) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *ListRunsResponse) GetLastID() string {
	if o == nil {
		return ""
	}
	return o.LastID
}

func (o *ListRunsResponse) GetObject() string {
	if o == nil {
		return ""
	}
	return o.Object
}
