// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListFineTunesResponse - OK
type ListFineTunesResponse struct {
	Data   []interface{} `json:"data"`
	Object string        `json:"object"`
}
