// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListPaginatedFineTuningJobsResponse - OK
type ListPaginatedFineTuningJobsResponse struct {
	Data    []FineTuningJob `json:"data"`
	HasMore bool            `json:"has_more"`
	Object  string          `json:"object"`
}

func (o *ListPaginatedFineTuningJobsResponse) GetData() []FineTuningJob {
	if o == nil {
		return []FineTuningJob{}
	}
	return o.Data
}

func (o *ListPaginatedFineTuningJobsResponse) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *ListPaginatedFineTuningJobsResponse) GetObject() string {
	if o == nil {
		return ""
	}
	return o.Object
}
