// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ModifyMessageRequestMetadata - Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.
type ModifyMessageRequestMetadata struct {
}

type ModifyMessageRequest struct {
	// Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.
	//
	Metadata *ModifyMessageRequestMetadata `json:"metadata,omitempty"`
}

func (o *ModifyMessageRequest) GetMetadata() *ModifyMessageRequestMetadata {
	if o == nil {
		return nil
	}
	return o.Metadata
}
