// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ModifyThreadRequestMetadata - Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.
type ModifyThreadRequestMetadata struct {
}

type ModifyThreadRequest struct {
	// Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.
	//
	Metadata *ModifyThreadRequestMetadata `json:"metadata,omitempty"`
}

func (o *ModifyThreadRequest) GetMetadata() *ModifyThreadRequestMetadata {
	if o == nil {
		return nil
	}
	return o.Metadata
}
