// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type MessageCreation struct {
	// The ID of the message that was created by this run step.
	MessageID string `json:"message_id"`
}

func (o *MessageCreation) GetMessageID() string {
	if o == nil {
		return ""
	}
	return o.MessageID
}

// RunStepDetailsMessageCreationObjectType - Always `message_creation`.
type RunStepDetailsMessageCreationObjectType string

const (
	RunStepDetailsMessageCreationObjectTypeMessageCreation RunStepDetailsMessageCreationObjectType = "message_creation"
)

func (e RunStepDetailsMessageCreationObjectType) ToPointer() *RunStepDetailsMessageCreationObjectType {
	return &e
}

func (e *RunStepDetailsMessageCreationObjectType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "message_creation":
		*e = RunStepDetailsMessageCreationObjectType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RunStepDetailsMessageCreationObjectType: %v", v)
	}
}

// RunStepDetailsMessageCreationObject - Details of the message creation by the run step.
type RunStepDetailsMessageCreationObject struct {
	MessageCreation MessageCreation `json:"message_creation"`
	// Always `message_creation`.
	Type RunStepDetailsMessageCreationObjectType `json:"type"`
}

func (o *RunStepDetailsMessageCreationObject) GetMessageCreation() MessageCreation {
	if o == nil {
		return MessageCreation{}
	}
	return o.MessageCreation
}

func (o *RunStepDetailsMessageCreationObject) GetType() RunStepDetailsMessageCreationObjectType {
	if o == nil {
		return RunStepDetailsMessageCreationObjectType("")
	}
	return o.Type
}
