// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ToolOutputs struct {
	// The output of the tool call to be submitted to continue the run.
	Output *string `json:"output,omitempty"`
	// The ID of the tool call in the `required_action` object within the run object the output is being submitted for.
	ToolCallID *string `json:"tool_call_id,omitempty"`
}

func (o *ToolOutputs) GetOutput() *string {
	if o == nil {
		return nil
	}
	return o.Output
}

func (o *ToolOutputs) GetToolCallID() *string {
	if o == nil {
		return nil
	}
	return o.ToolCallID
}

type SubmitToolOutputsRunRequest struct {
	// A list of tools for which the outputs are being submitted.
	ToolOutputs []ToolOutputs `json:"tool_outputs"`
}

func (o *SubmitToolOutputsRunRequest) GetToolOutputs() []ToolOutputs {
	if o == nil {
		return []ToolOutputs{}
	}
	return o.ToolOutputs
}
