// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TranscriptionSegment struct {
	// Average logprob of the segment. If the value is lower than -1, consider the logprobs failed.
	AvgLogprob float32 `json:"avg_logprob"`
	// Compression ratio of the segment. If the value is greater than 2.4, consider the compression failed.
	CompressionRatio float32 `json:"compression_ratio"`
	// End time of the segment in seconds.
	End float32 `json:"end"`
	// Unique identifier of the segment.
	ID int64 `json:"id"`
	// Probability of no speech in the segment. If the value is higher than 1.0 and the `avg_logprob` is below -1, consider this segment silent.
	NoSpeechProb float32 `json:"no_speech_prob"`
	// Seek offset of the segment.
	Seek int64 `json:"seek"`
	// Start time of the segment in seconds.
	Start float32 `json:"start"`
	// Temperature parameter used for generating the segment.
	Temperature float32 `json:"temperature"`
	// Text content of the segment.
	Text string `json:"text"`
	// Array of token IDs for the text content.
	Tokens []int64 `json:"tokens"`
}

func (o *TranscriptionSegment) GetAvgLogprob() float32 {
	if o == nil {
		return 0.0
	}
	return o.AvgLogprob
}

func (o *TranscriptionSegment) GetCompressionRatio() float32 {
	if o == nil {
		return 0.0
	}
	return o.CompressionRatio
}

func (o *TranscriptionSegment) GetEnd() float32 {
	if o == nil {
		return 0.0
	}
	return o.End
}

func (o *TranscriptionSegment) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *TranscriptionSegment) GetNoSpeechProb() float32 {
	if o == nil {
		return 0.0
	}
	return o.NoSpeechProb
}

func (o *TranscriptionSegment) GetSeek() int64 {
	if o == nil {
		return 0
	}
	return o.Seek
}

func (o *TranscriptionSegment) GetStart() float32 {
	if o == nil {
		return 0.0
	}
	return o.Start
}

func (o *TranscriptionSegment) GetTemperature() float32 {
	if o == nil {
		return 0.0
	}
	return o.Temperature
}

func (o *TranscriptionSegment) GetText() string {
	if o == nil {
		return ""
	}
	return o.Text
}

func (o *TranscriptionSegment) GetTokens() []int64 {
	if o == nil {
		return []int64{}
	}
	return o.Tokens
}
